use_frameworks!

target 'UIKitExtensions_Example' do
  pod 'UIKitExtensions', :path => '../'

#  pod 'UIKitExtensions/UIColor', :path => '../'

  target 'UIKitExtensions_Tests' do
    inherit! :search_paths

    
  end
end
